### ISSUE TITLE
Weird Each Child in a list should have a unique "key" prop, Check the render method of 'Courses' & list students(When viewed courses page)

### ISSUE THREAD

**Issue by SenpaiSumpie** [QJMTech/TeamBandit#47]
This issue seems pretty prevalent and may correspond to why when you edit a field from the database it adds it to the bottom. But this again shouldnt be to big of a deal as we want to rearrange features.

**Comment by LScholl63** [comment]
I don't see this when viewing the courses page. Only the email hub (And I think it's on purpose for simplicity for now). This is because dummy contacts are currently being used and it's just a simple list as of now with no unique id's. I believe the key prop needs to be added in the map to the MessageCard component in MessageList.js

If this is not the issue stated, feel free to have this comment deleted, but I only see this warning when going to the email hub.
